### ISSUE TITLE
Tile use and using this library

### ISSUE THREAD

**Issue by programmin1** [nzjrs/osm-gps-map#69]
I don't know if this has been resolved elsewhere, but where does this library stand as to the tile usage policy on https://operations.osmfoundation.org/policies/tiles/ ?

For example, "Bulk downloading is strongly discouraged. Do not download tiles unnecessarily."
My app, as well as everyone else who has build something off the example, has the cache functionality built in and is an awesome feature of this library. Is there is any required adjustment to the config, or need to register my app in addition to what work Osm GPS library does?

**Comment by dreadnought** [comment]
I implemented some changes to make it more compliant to OSM policy in 2016 (see #47 and #48). Caching is not necessarily the same as bulk downloading. When a tile, that was downloaded while you where browsing the map, gets written to a file cache, it's actually taking load of the server. Regarding a bulk downloading feature I see the app developers responsible, not the library. That's why I implemented the user agent option, to avoid collateral damage.

**Comment by johnny-bit** [comment]
using `user-agent` property, along with proper cache management on app devs part should alleviate all problems regarding tile use and bulk download use.

I've added the `user-agent` property to `mapviewer.c` example file. Should we stress it's importance in docs?

**Comment by johnny-bit** [comment]
With release 1.2.0 this won't be a problem I think.
