### ISSUE TITLE
manage tracks across the date change line

### ISSUE THREAD

**Issue by paolobenve** [nzjrs/osm-gps-map#88]
a segmente like `(lat=0º, lon=-179º) -> (lat=0º, lon=+179º)` is currently drawn as a line across almost all the equator, while it should be drawn across the date change line, i.e., on the opposite side.

I think that it would be enough to check if the ðlon is > 180º, and  in that case a segment like `(lat=0º, lon=-179º) -> (lat=0º, lon=+179º)` will become two segments `(lat=0º, lon=-179º) -> (lat=0º, lon=-180º)` + `(lat=0º, lon=+180º) -> (lat=0º, lon=+179º)`.

I'm thinking in lines 297-298 of `osm-gps-map-track.c`

Is it possible? i.e., is admitted that a track has two separete segments?

**Comment by johnny-bit** [comment]
I wouldn't separate track into segments if possible. Wouldn't it be better to focus on drawing part rather than track part?

**Comment by paolobenve** [comment]
ok, let me work on the darktable patch

**Comment by johnny-bit** [comment]
To semi-answer your question raised in darktable issue.

Current readme states:
> osm-gps-map is a Gtk mapping widget (and Python bindings) that when given
GPS co-ordinates, draws a GPS track, and points of interest on a moving map
display.

since there's no qualifier around drawing track, the user of the widget (so app developer) might assume that the widget does "the smart thing".

Easy way out would be to add caveat that paths crossing date change line are not supported and have to be split... But that wouldn't be nice since we're handling Greenwich line correctly despite +/- sign change... So IMO if the handling could be improved on here it would be the best way.

**Comment by paolobenve** [comment]
what is the function that draws the lines?

**Comment by johnny-bit** [comment]
I think it should be `osm_gps_map_print_track` in `osm-gps-map-widget.c` or around that...

**Comment by paolobenve** [comment]
I prepared the PR, but I cannot understand if darktable is using my version of osmgpsmap (which should be in `/usr/local/lib`) or the older one...

**Comment by phweyland** [comment]
> a segmente like `(lat=0º, lon=-179º) -> (lat=0º, lon=+179º)` is currently drawn as a line across almost all the equator, while it should be drawn across the date change line, i.e., on the opposite side.

Not always, depends on start and end dates. If I'm not mistaken doesn't manage datetime on tracks.

**Comment by johnny-bit** [comment]
darktable's cmake by default searches system paths. I bet you can force cmake to use your lib instead of global... I think people did that with exiv2 and CR3 compilling. Sorry I can't be much of help, busy weeks :/
